Site:http://web.stanford.edu/class/cs20si/

Lecture: 
Step 1: Assemble a graph
Step 2: User a session to execute the graph

What is a Tensor?
0-d Tensor - Scalar
1-d Tensor - Vector
2-d Tensor - Matrix
..so on

In [1]:
import tensorflow as tf

In [3]:
a = tf.add(2,3)
print(a)

Tensor("Add_1:0", shape=(), dtype=int32)


Printing a does not give the result, but it gives the node information. The node has not been executed.

In [5]:
b = tf.add(3.0, 5.0)
print(b)

Tensor("Add_3:0", shape=(), dtype=float32)


Tensors are just data. 
Data Flow is the Tensor flow graph
Now how to get the value of a and b. Run it as part of session. Running in a session means that running with all available resources.

In [7]:
#Create a session; Run the code for 'a' and print the result.
sess = tf.Session()
print(sess.run(a)) # Tensor looks at value of node a and calculates the node value.
sess.close()

5


In [8]:
with tf.Session() as sess:
    print(sess.run(a)) # Using "With"

5


tf.Session(): A Session object encapsulates the environment in which Operation objects are executed and Tensor objects are evaluated.

### Another Tensor graph

In [13]:
x = 2
y = 3
op1 = tf.add(x,y)
op2 = tf.multiply(x,y)
op3 = tf.pow(op2, op1)
with tf.Session() as sess:
    op3 = sess.run(op3)
    print(op3)

7776


In the above example; just running the node for op3 enumerates all the previous nodes which are required to evaluate op3

In [14]:
x = 2
y = 3
op1 = tf.add(x,y)
op2 = tf.multiply(x,y)

useless = tf.multiply(x, op1)

op3 = tf.pow(op2, op1)
with tf.Session() as sess:
    op3 = sess.run(op3)
    print(op3)

7776


useless is not required in the sess.run for op3; 'useless' is not evaulated. If we need to get output then it will be run

In [19]:
with tf.Session() as sess:
    k = sess.run([useless])
print(k)

[10]


The computations are divided into graphs and subgraphs and each sub-graph cna be evaluated independently on different kind of machines.

In [38]:
# General Matrix mulitplication
a = tf.constant([2.0, 5.0, 3.0, 4.0], shape = [2,2], name = 'a')
b = tf.constant([2.0, 5.0,9.0, 7.0], shape = [2,2], name = 'b')
c = tf.matmul(a,b)

with tf.Session() as sess: 
    print(sess.run(c))

[[ 49.  45.]
 [ 42.  43.]]


In [40]:
# Distributed Computation on specific device
with tf.device('/cpu:0'):
    a = tf.constant([2.0, 5.0, 3.0, 4.0], shape = [2,2], name = 'a')
    b = tf.constant([2.0, 5.0,9.0, 7.0], shape = [2,2], name = 'b')
    c = tf.matmul(a,b)
    
# Create a session with log_device_placement set to true
sess = tf.Session(config = tf.ConfigProto(log_device_placement = True))

# Run the op
print(sess.run(c))

[[ 49.  45.]
 [ 42.  43.]]


What about ore graph?
Tensorflow provides default graph. You can build more graphs, but recommendation is to use one graph.

### Why Graphs?
Lecture covers a discussion on creating a new graph and adding node to it for computation. General reco from course instructor is to use only 1 graph. 

Why use graphs though ?
- We can partition graphs and run the subgraphs that are relevant for particular computation.
- Partiton the computation logic into smaller pieces which can be then distributed to different gpu/cps
- Directed Acyclyic graph models are used in Neural networks and this architecture aligns with that.

In [44]:
#Visualizing the graph with tensor board

a = tf.constant(2, name = "AAA")
b = tf.constant(3, name = "BBB")
x = tf.add(a,b, name = "ADDITION")

with tf.Session() as sess:
    #
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
writer.close() 
#Note that the graph contains previously defined variables as well.

5


To launch tensorboard do the following:
1. Launch a new python terminal
2. Type : source activate tensorflow . This activates a tensornflow python environemnt
3. type tensorboard --logdir=/home/anm/projects/python/tf/graphs

### Tensor Constants

In [11]:
#signature of constant

#tf.constant(value, dtype = None, shape = None, name = 'Const', verify_shape = False)
# 
# Verify shape: Provide value and shape; if the value does not match the shape provided:- it will throw false

# = tf.constant(2, shape = [2,2],verify_shape = True)  # Throws an error
b = tf.constant(5,shape = [2,2]) #verify_shape by default = False; hence no error

with tf.Session() as sess:
    print(sess.run(b))

#With verify_shape = False, it just duplicated to match the shape of 3x3

[[5 5]
 [5 5]]


In [15]:
# More Constants

a = tf.constant([2,2], name = "a")
b = tf.constant([[0,1],[2,3]], name = "b")
x = tf.add(a,b, name = "add")
y = tf.multiply(a,b, name  = "mul") # Elementwise multipcation
with tf.Session() as sess:
    x, y = sess.run([x,y])
    print(x,"\n\n", y)

[[2 3]
 [4 5]] 

 [[0 2]
 [4 6]]


In [16]:
#tf.zeros(shape, dtype = tf.float32, name = None)
k = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(k))

[[0 0 0]
 [0 0 0]]


In [17]:
#tf.ones(shape, dtype = tf.float32, name = None, optmize = True)
k = tf.ones([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(k))

[[1 1 1]
 [1 1 1]]


In [19]:
input_tensor = tf.zeros([5,5], tf.int32)
output_tensor = tf.ones_like(input_tensor) # Tensor has a shape of another tensor.
with tf.Session() as sess:
    print(sess.run(output_tensor))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
# Tensor filled with specific vaue

#tf.fill(dims, value, name = None)
u = tf.fill([2,3],8)
with tf.Session() as sess:
    print(sess.run(u))

[[8 8 8]
 [8 8 8]]


In [26]:
#Sequences and ranges support in tensorflow
#tf.linspace(start, stop , num, name = None)

#u = tf.linspace(10,20.0,2) # Having integer values throws error
v = tf.linspace(10.0,20.0,4)
with tf.Session() as sess:
    #print(sess.run(u))
    print(sess.run(v))

[ 10.          13.33333302  16.66666603  20.        ]


In [29]:
u = tf.range(0,12,3)
v = tf.range(0,12)
with tf.Session() as sess:
    print(sess.run(u))
    print(sess.run(v))

[0 3 6 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


Tensor objects are not iterable. Hence the following code will be in error
for i in tf.range(4): will throw an error

### Randomly Generated Constants

In [32]:
#Normal distribution
a = tf.random_normal([1,10], mean = 0, stddev = 1)
with tf.Session() as sess:
    print(sess.run(a))

[[ 0.64062023  0.23424713 -1.15992284  1.6687305   2.19163203 -0.09299777
  -1.16985631  2.08277416  0.11149438 -0.17422791]]


In [34]:
# If the numbers generated are 2SD away from mean, that point will be resampled; hence technically all points sampled are
# within 2SD of mean.
a = tf.truncated_normal([1,10], mean = 0, stddev = 1)
with tf.Session() as sess:
    print(sess.run(a))

[[ 1.29168046 -1.52571726 -0.8403278   1.84704411  0.33465579 -0.34765878
  -0.4465      0.95861709 -1.19733107  0.16889538]]


In [37]:
# Generate data from Uniform distribution.
a = tf.random_uniform([1,10], minval = 0, maxval = 1, dtype = tf.float32, seed = None, name = None)
with tf.Session() as sess:
    print(sess.run(a))

[[ 0.4627496   0.4699893   0.24381638  0.40396512  0.42248762  0.64823556
   0.31833065  0.37038064  0.46237147  0.08211207]]


In [39]:
# Order of the rows of the elements are changed.
a = tf.random_shuffle([[1,2],[3,4],[5,6]], seed = None, name = None)
with tf.Session() as sess:
    print(sess.run(a))

[[5 6]
 [1 2]
 [3 4]]


In [53]:
# In this case, the row order is preserved but the 'depth' order can be changed. Called shuffling on 1st dimension
a = tf.random_shuffle([[[1,2],[3,4],[5,6]],[[11,22],[33,44],[55,66]]], seed = None, name = None)
with tf.Session() as sess:
    print(sess.run(a))

[[[11 22]
  [33 44]
  [55 66]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]]]


In [65]:
#tf.random_crop
#size = height and width of the cropping; here we say 2 height and 3 width
a = tf.random_crop([[1,2,3,4,5,6,7],[11,22,33,44,55,66,77],[111,222,333,444,555,666,777]], size = [2,2])
with tf.Session() as sess:
    print(sess.run(a))

[[ 22  33]
 [222 333]]


In [73]:
# tf.multinomial
import numpy as np
b = tf.constant(np.random.normal(size = (3,4)))
# we take b as the log of probability value

a = tf.multinomial(b,5) # we take sample value
with tf.Session() as sess:
    print(sess.run(b))
    print(sess.run(a))
        # The output is 3x4
        # Each row of bcontains log probability of the 4 classes.
        # Each element in row of 'a' is then selecting and element from 0-3 classes based on log probability
print("\nOne more try\n")
a = tf.multinomial(b,10) # we take sample value
with tf.Session() as sess:
    print(sess.run(b))
    print(sess.run(a))

[[ 1.47426713 -1.41061131 -1.51584831  0.54189419]
 [-0.67729004 -0.31259853 -1.64196458 -0.12368025]
 [ 1.71104929 -0.80819546  0.16372978 -0.88884077]]
[[2 0 1 3 3]
 [0 3 1 3 1]
 [2 2 0 0 0]]

One more try

[[ 1.47426713 -1.41061131 -1.51584831  0.54189419]
 [-0.67729004 -0.31259853 -1.64196458 -0.12368025]
 [ 1.71104929 -0.80819546  0.16372978 -0.88884077]]
[[1 0 3 3 3 0 0 3 0 0]
 [1 1 1 1 0 3 1 1 3 0]
 [2 0 3 1 0 0 0 1 0 0]]


In [ ]:
# tf.random_gamma : Look up gamma distribution.

In [75]:
# setting random seed for the entire graph
tf.set_random_seed(5)

More Operations
1. Element wise: Add, Sub, Multiply, Div, Exp, Log, Greater, Less, equal ..
2. Array Operation: Concat, Slice, split, Constant, Rank, Shape, Shuffle
3. Matrix: MatMul, MatrixInverse, MatrixDeterminant

3. Stateful Operations: Variable, Assign, AssignAdd 
4. Neural N/w: SoftMax, Sigmoid, ReLU, Convolution2D, MaxPool
5. Checkpointing operations: Save, Restore
6. Queue and Sync operations: Enqueue, Dequeue, MutexAcquire, MutexRelease
7. Control flow operations: Merge, Switch, Enter, Leave, NextIteration



In [77]:
#Operations
a = tf.constant([3,6])
b = tf.constant([2,2])
u = tf.add(a,b)
v = tf.add_n([a,b,b])
w= tf.multiply(a,b)
#tf.matmul(a,b) Error
x = tf.matmul(tf.reshape(a,[1,2]), tf.reshape(b,[2,1]))
y = tf.div(a,b)
z = tf.mod(a,b)

with tf.Session() as sess:
    print(sess.run(u))
    print(sess.run(v))
    print(sess.run(w))
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))

[5 8]
[ 7 10]
[ 6 12]
[[18]]
[1 3]
[1 0]


### Tensorflow DataTypes

TensorFlow takes Python native types: boolean, numeric(int, float), string

In [80]:
t_0 = 19
u = tf.zeros_like(t_0)
v = tf.ones_like(t_0)

with tf.Session() as sess:
    print(sess.run(u))
    print(sess.run(v))

0
1


In [82]:
t_1 = ['apple','peach','banana']
u = tf.zeros_like(t_1)
#v = tf.ones_like(t_1) #throws an error because not clear what concent on ones is for a string

with tf.Session() as sess:
    print(sess.run(u))



[b'' b'' b'']


In [84]:
t_2 = [[True,False,False],[False,False,True],[False,True,False]]
u = tf.zeros_like(t_2)
v = tf.ones_like(t_2)

with tf.Session() as sess:
    print(sess.run(u))
    print(sess.run(v))

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Variables

In [85]:
a = tf.Variable(2) #scalar
b = tf.Variable([2,3]) #vector 
c = tf.Variable([[1,2],[3,4]]) #matrix
W = tf.Variable(tf.zeros([784,10])) #784x10 matrix

In [86]:
# Variables support various methods
x = tf.Variable(2)

# x.initializer #initializer op
# x.value() # read operation
# x.assign(..) #Write operation
# x.assign_add(..) #?

In [87]:
# You have always to initialize your variables

#e.g
# init = tf.global_variables_initializer()
# with tf.Session() as sess:
#    sess.run(init)

# Initializing speicifc variables:
# init_ab = tf.variables_initializer([a,b])
# with tf.Session() as sess:
#    sess.run(init_ab)

# Initialize a single variable
# W = tf.Variable(tf.zeros([10,10]))
# with tf.Session() as sess:
#    sess.run(W.initializer)

In [91]:
#Eval() a variable

W = tf.Variable(tf.truncated_normal([5,5]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[-0.11400997 -0.18153206  0.73489761 -1.72972417  0.31975889]
 [-1.64710903 -0.78185093  1.82349503  0.43927184 -1.33728075]
 [-0.69384336  0.05222709 -0.16475578 -1.30621588 -0.53799629]
 [ 0.385288    1.6380235  -1.44918716  0.15697786  1.53815043]
 [ 1.242769    0.54607153  1.21899426  0.0025931   0.60515374]]


In [94]:
#tf.Variable.assing()

W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval()) # Did not call W.assign(100) hence the value was never changed.

10


In [96]:
#tf.Variable.assing()

W = tf.Variable(10)
assign_op= W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval()) # Did not call W.assign(100) hence the value was never changed.

100


In [104]:
# MOre example

my_var = tf.Variable(2)
my_var2 = my_var.assign(2*my_var) # Note that my_var2 is 'assigned' from value at my_Vvar

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var))
    print(sess.run(my_var))
    print(sess.run(my_var2))
    print(sess.run(my_var2))
    

2
2
4
8


In [107]:
# Assign_add and #Assign_sub; 
my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    
    #increment by 10
    print(sess.run(my_var.assign_add(10)))
    
    
    #subtract 2
    print(sess.run(my_var.assign_sub(2)))

20
18


In [110]:
# Each session maintains its own copy of the variable

W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10))) # W has different value in Session 1 thans in Session 2
print(sess2.run(W.assign_sub(10)))

sess1.close()
sess2.close()

20
0


In [ ]:
# Using a variable to initialze another variable.

W = tf.Variable(tf.truncated_normal([10,10]))
#U = tf.Variable(2 * W) ENsure W is initialized before
U = tf.Variable(2*W.initialized_value())

In [111]:
# Control Dependencies
# Defines which ops should be run first

# with g.control_dependencies([a,b,c]):
    # d and e will only run after a, b, and c have exectued
#    d = 
#    e = 

In [112]:
#Placeholders
#A TF program has 2 phase. 1 phas for gathering the graph nodes and 2nd for using a session to execute operations

a = tf.placeholder(tf.float32, shape = [3])

b = tf.constant([5,5,5], tf.float32)
c = a + b

#Need to feed the value to a before running
with tf.Session() as sess:
    print(sess.run(c,{a: [1,2,3]})) # tensor name is the key in dict and dictionary values are values that we want to feed


[ 6.  7.  8.]


In [114]:
# Multiple data points for placeholder:
#Placeholders
#A TF program has 2 phase. 1 phas for gathering the graph nodes and 2nd for using a session to execute operations

a = tf.placeholder(tf.float32, shape = [3])

b = tf.constant([5,5,5], tf.float32)
c = a + b

#Need to feed the value to a before running
with tf.Session() as sess:
    for k in range(5): # Call the image in loop.
        print(sess.run(c,{a: [1,2,k]})) # tensor name is the key in dict and dictionary values are values that we want to feed


[ 6.  7.  5.]
[ 6.  7.  6.]
[ 6.  7.  7.]
[ 6.  7.  8.]
[ 6.  7.  9.]


In [116]:
# feed_dict

a = tf.add(2,5)
b = tf.multiply(a,3)

with tf.Session() as sess:
    replace_dict ={a:15} # new value for a
    print(sess.run(b,feed_dict = replace_dict)) #sess.run can take a second argument as the dicitionary.
    
    

45


In [122]:
#Normal loading:
x = tf.Variable(10)
y = tf.Variable(20)
z = tf.add(x,y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(5):
        print(sess.run(z))

30
30
30
30
30
30
30
30
30
30


In [125]:
# Lazy Loading
#Normal loading:
x = tf.Variable(10)
y = tf.Variable(20)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(5):
        print(sess.run(tf.add(x,y)))

30
30
30
30
30
